### ISSUE TITLE
Question about the gt generation from nuscenes

### ISSUE THREAD

**Issue by ypfFromWhu** [Tsinghua-MARS-Lab/neural_map_prior#10]
Thanks for you all the work, but I have learned the code, there is some problem about the RaseterizedData class's get_lineimg function which generate the seg_map, inst_mask and direction_mask. Is there any detailed explanation documents about it? Thanks and hope for your answers.

**Comment by ypfFromWhu** [comment]
And I see the loss is the Hdmapnet loss, why we don't regress the vector directly, is there any experiment about it?

**Comment by abbyxxn** [comment]
This portion of the code might indeed not be easy to understand. And it is based on the code in [HDMapNet](https://github.com/Tsinghua-MARS-Lab/HDMapNet) and the code in [VectorMapNet_code](https://github.com/Mrmoore98/VectorMapNet_code). I refer you to find some useful answers there.

**Comment by ypfFromWhu** [comment]
你好，你的邮件我已收到，会尽快给你回复。

**Comment by ypfFromWhu** [comment]
你好，你的邮件我已收到，会尽快给你回复。
