### ISSUE TITLE
How can I adjust the data_sample. py if I want to evaluate NMP

### ISSUE THREAD

**Issue by FUN314** [Tsinghua-MARS-Lab/neural_map_prior#13]
我要评估NMP的话该如何调整data_sample.py文件呢

**Comment by abbyxxn** [comment]
Thank you for your interest in our code. For Neural Map Prior, whether it is for training or evaluation, it is necessary to reallocate the samples to each GPU. I have written the function on how to correspond samples with GPUs [here](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/project/neural_map_prior/datasets/nuscenes_dataset.py#L491). The data_sample only takes responsibility for loading the samples as I have allocated them, without any other special content.
