### ISSUE TITLE
NMP results download issue

### ISSUE THREAD

**Issue by canteen-man** [Tsinghua-MARS-Lab/neural_map_prior#15]
你好
NMP result那个链接下载的文件只有11M.
我猜测是因为google drive把这6000多个文件打包的时候总是打包不全。
您可以直接将您的1G的zip文件上传吗。
谢谢。

**Comment by abbyxxn** [comment]
我上传了6016张图，虽然比原始验证集6019少了三张，但应该是全了

**Comment by canteen-man** [comment]
感谢你的回复。
上传的数据是全的，但是download的时候，google drive打包成压缩包时，是google drive打包不对。
我才发现在本地跑test.py也可以存储这些。
