### ISSUE TITLE
new division of the data set

### ISSUE THREAD

**Issue by missTL** [Tsinghua-MARS-Lab/neural_map_prior#18]
How can I get the new division of the data set in the paper?

**Comment by abbyxxn** [comment]
Thank you for your interest in our project. I believe you are referring to the NuScenes Boston Split. Someone else has raised the same question before [issue 16](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/issues/16), and I have uploaded the code for generating the Boston split [here](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/tree/main/project/neural_map_prior/data_utils/boston_split_gen).
