### ISSUE TITLE
Question about Dataset Preparation

### ISSUE THREAD

**Issue by yzdad** [Tsinghua-MARS-Lab/neural_map_prior#4]
I have run the nuscenes_converter:

python tools/data_converter/nuscenes_converter.py --data-root your/dataset/nuScenes/

and it generated nuscenes_map_infos_train.pkl and nuscenes_map_infos_val.pkl, but I find they are different from the provided files nuScences_map_trainval_infos_train.pkl and nuScences_map_trainval_infos_val.pkl.
Also, could you provide the script for generating train_city_infos.pkl and val_city_infos.pkl? And, the nuScenes Dataset Structure does not display where the map extensions (V1.3) should be placed.

**Comment by xuwanyan1998** [comment]
Same situation with @yzdad, when decoding the pkl files, the 'infos' of each data are different with the provided pkl files and generated pkl files, the 'infos' provided by @abbyxxn have **_16_** arritbutions, such as "lidar_path, token, sweeps, ... , ego2global_rotaion, gt_boxes, gt_names", but the 'infos' generated by 'tools/data_converter/nuscenes_converter.py' hase only **_10_** attributions. Is there another generation way for the pkl files?

**Comment by abbyxxn** [comment]
@yzdad @xuwanyan1998 Thank you for your interest in this project. I have updated the file ['tools/data_converter/nuscenes_converter.py'](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/main/tools/data_converter/nuscenes_converter.py), which should now include the generation of the required 16 attributes. Additionally, I have uploaded the code for generating ['city_infos'](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/main/project/neural_map_prior/data_utils/nusc_city_infos.py). 'city_infos' is simply a list containing city names in the same order as 'nuScences_map_trainval_infos_{dataset}.pkl'. 'map extensions' should be placed under the 'maps' folder.
