### ISSUE TITLE
map_slice_float_dict generation

### ISSUE THREAD

**Issue by xuwanyan1998** [Tsinghua-MARS-Lab/neural_map_prior#5]
Hi !@abbyxxn  appreciate for your great work! When I try to finetune with the NMP after training the baseline BEVFormer for 24 epoch on v1.0-mini dataset, I met the following problem:

> start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
\* 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
epoch: 0 self.train_epoch_point: -2
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.31s/it]
gpu_id: 0 count: tensor(0.) gpu_city_list ['boston-seaport_map_2_1']
create empty map for: map_slice_float_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'float32', 'embed_dims': 256, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.76it/s]
gpu_id: 0 count: tensor(0) gpu_city_list ['boston-seaport_map_2_1']
create empty map for: map_slice_int_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'int16', 'embed_dims': 1, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
Traceback (most recent call last):
  File "tools/train.py", line 279, in <module>
    main()
  File "tools/train.py", line 275, in main
    meta=meta)
  File "/neural_map_prior/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/usr/local/lib/python3.6/dist-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/neural_map_prior/project/neural_map_prior/models/mapers/base_mapper.py", line 122, in train_step
    loss, log_vars, num_samples = self(**data_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/neural_map_prior/project/neural_map_prior/models/mapers/base_mapper.py", line 90, in forward
    return self.forward_train(*args, **kwargs)
  File "/neural_map_prior/project/neural_map_prior/models/mapers/original_hdmapnet.py", line 239, in forward_train
    preds_dict = self.forward_single(imgs, **kwargs)
  File "/neural_map_prior/project/neural_map_prior/models/mapers/original_hdmapnet.py", line 131, in forward_single
    self.gm.take_map_prior(prior_bev[ib:ib + 1], token, img_meta, 'train', trans)
  File "/neural_map_prior/project/neural_map_prior/models/mapers/map_global_memory.py", line 237, in take_map_prior
    global_map_slice = self.map_slice_float_dict[f'map_{city_name}_{map_index[0]}_{map_index[1]}']
KeyError: 'map_singapore-hollandvillage_2_0'

When I tried to locate the variable of **self.map_slice_float_dict**, I found this dict variable only have one key which is **'map_boston-seaport_2_1'**
Did I load the data in a wrong way or something?

**Comment by abbyxxn** [comment]
Could you try replacing the root and filename of these two functions, [load_nusc_data_infos](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/8519e06a0a893898209f0510ebbdd6965e9d5e1f/project/neural_map_prior/map_tiles/lane_render.py#L213) and [load_nusc_data_cities](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/8519e06a0a893898209f0510ebbdd6965e9d5e1f/project/neural_map_prior/map_tiles/lane_render.py#L223)  with 'mini's info root and filename, and also make sure you are running the newly written [GeoDistributedSampler](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/8519e06a0a893898209f0510ebbdd6965e9d5e1f/tools/data_sampler.py#L34).

**Comment by xuwanyan1998** [comment]
Sorry, I didn't figure out how to use the newly datasampler. In the [getting_started.md](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/main/docs/getting_started.md), you said:

> In our setup, we need to manually replace mmdet mmdet/apis/train.py with ours tools/mmdet_train.py to add a new custom data_sampler. 

Should I just copy the new mmdet_train.py to the path of  installed package **mmdet/apis/**, and rename the **mmdet_train.py** to **train.py**, but how this **data_sampler.py** to be called when prepare the data.

**Comment by abbyxxn** [comment]
> Sorry, I didn't figure out how to use the newly datasampler. In the [getting_started.md](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/main/docs/getting_started.md), you said:
> 
> > In our setup, we need to manually replace mmdet mmdet/apis/train.py with ours tools/mmdet_train.py to add a new custom data_sampler.
> 
> Should I just copy the new mmdet_train.py to the path of installed package **mmdet/apis/**, and rename the **mmdet_train.py** to **train.py**, but how this **data_sampler.py** to be called when prepare the data.

Yes, you should copy the new mmdet_train.py to the path of the installed package mmdet/apis/, and rename the mmdet_train.py to train.py. Please note that this step will modify the default sampler behavior. I have also considered other methods, but they are being tested. And adding 'tools' to the PYTHONPATH so that it will reference 'data_sampler.py'.

**Comment by xuwanyan1998** [comment]
> Hi !@abbyxxn appreciate for your great work! When I try to finetune with the NMP after training the baseline BEVFormer for 24 epoch on v1.0-mini dataset, I met the following problem:
> 
> > start before_train_epoch removing map_slice_float_dict content !!!!!!!!!!!!!!!
> > \* 3 start before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> > end before_train_epoch removing map_slice_int_dict content !!!!!!!!!!!!!!!
> > epoch: 0 self.train_epoch_point: -2
> > 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.31s/it]
> > gpu_id: 0 count: tensor(0.) gpu_city_list ['boston-seaport_map_2_1']
> > create empty map for: map_slice_float_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'float32', 'embed_dims': 256, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
> > 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.76it/s]
> > gpu_id: 0 count: tensor(0) gpu_city_list ['boston-seaport_map_2_1']
> > create empty map for: map_slice_int_dict, {'root_dir': '/localdata_ssd/map_slices/raster_global_map', 'type': 'rasterized', 'prefix': 'map_large_reso_gru_cpu', 'tile_param': {'data_type': 'int16', 'embed_dims': 1, 'num_traversals': 1}, 'batch_size': 8, 'single_gpu': False, 'global_map_tile_size': [4, 4], 'global_map_raster_size': [0.3, 0.3]}
> > Traceback (most recent call last):
> > File "tools/train.py", line 279, in 
> > main()
> > File "tools/train.py", line 275, in main
> > meta=meta)
> > File "/neural_map_prior/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
> > meta=meta)
> > File "/usr/local/lib/python3.6/dist-packages/mmdet/apis/train.py", line 170, in train_detector
> > runner.run(data_loaders, cfg.workflow)
> > File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> > epoch_runner(data_loaders[i], **kwargs)
> > File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
> > self.run_iter(data_batch, train_mode=True, **kwargs)
> > File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
> > **kwargs)
> > File "/usr/local/lib/python3.6/dist-packages/mmcv/parallel/distributed.py", line 52, in train_step
> > output = self.module.train_step(*inputs[0], **kwargs[0])
> > File "/neural_map_prior/project/neural_map_prior/models/mapers/base_mapper.py", line 122, in train_step
> > loss, log_vars, num_samples = self(**data_dict)
> > File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> > result = self.forward(*input, **kwargs)
> > File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
> > return old_func(*args, **kwargs)
> > File "/neural_map_prior/project/neural_map_prior/models/mapers/base_mapper.py", line 90, in forward
> > return self.forward_train(*args, **kwargs)
> > File "/neural_map_prior/project/neural_map_prior/models/mapers/original_hdmapnet.py", line 239, in forward_train
> > preds_dict = self.forward_single(imgs, **kwargs)
> > File "/neural_map_prior/project/neural_map_prior/models/mapers/original_hdmapnet.py", line 131, in forward_single
> > self.gm.take_map_prior(prior_bev[ib:ib + 1], token, img_meta, 'train', trans)
> > File "/neural_map_prior/project/neural_map_prior/models/mapers/map_global_memory.py", line 237, in take_map_prior
> > global_map_slice = self.map_slice_float_dict[f'map_{city_name}_{map_index[0]}_{map_index[1]}']
> > KeyError: 'map_singapore-hollandvillage_2_0'
> 
> When I tried to locate the variable of **self.map_slice_float_dict**, I found this dict variable only have one key which is **'map_boston-seaport_2_1'** Did I load the data in a wrong way or something?

I figure out why this dismatch will happen. I'm tring to train stage 2 with 1 GPU, but the batchsize in the config file is set to 8, so the **gpu_city_list** only have 1 map tile, when I set the batchsize to 1, the **gpu_city_list** increase to 47. I wonder how  these maps  were devided to the gpus, the 47 **gpu_city_list** consisit of 12 _boston-seaport_map_, 13 _singapore-onenorth_map_, 11 _singapore-queenstown_map_, and 11 _singapore-hollandvillage_map_. Why these maps were devided to 11/13 parts not 9/12/16 parts.

**Comment by xuwanyan1998** [comment]
And the **embed_reg_loss** is always 0.0000 when training the stage 1 or stage 2, is this normal?

**Comment by abbyxxn** [comment]
I roughly understand that there are 47 samples in nusc mini. These samples consist of 12 from the boston-seaport_map, 13 from singapore-onenorth_map, 11 from singapore-queenstown_map, and 11 from singapore-hollandvillage_map. I'm wondering what this "Why these maps were divided into 11/13 parts not 9/12/16 parts." means?

**Comment by abbyxxn** [comment]
> 
This is normal; we can overlook this loss and primarily consider the 'seg_loss'.

**Comment by abbyxxn** [comment]
> And the **embed_reg_loss** is always 0.0000 when training the stage 1 or stage 2, is this normal?

This is normal; we can overlook this loss and primarily consider the 'seg_loss'.

**Comment by xuwanyan1998** [comment]
> 

When I train the model on the 0.1-trainval dataset, I set the batchsize=1, using 1 gpu, when devide the map tiles for each gpu, the gpu_city_list number is 47, like 

> ['boston-seaport_map_2_1', 'boston-seaport_map_1_2', 'boston-seaport_map_0_3', 'boston-seaport_map_3_1', 'boston-seaport_map_1_1', 'boston-seaport_map_0_2', 'boston-seaport_map_2_2', 'boston-seaport_map_0_0', 'boston-seaport_map_1_3', 'boston-seaport_map_0_1', 'boston-seaport_map_1_0', 'boston-seaport_map_3_2', 
> 'singapore-onenorth_map_1_2', 'singapore-onenorth_map_0_1', 'singapore-onenorth_map_2_3', 'singapore-onenorth_map_2_2', 'singapore-onenorth_map_1_1', 'singapore-onenorth_map_1_3', 'singapore-onenorth_map_0_2', 'singapore-onenorth_map_3_1', 'singapore-onenorth_map_3_0', 'singapore-onenorth_map_2_1', 'singapore-onenorth_map_2_0', 'singapore-onenorth_map_0_0', 'singapore-onenorth_map_3_2', 
> 'singapore-queenstown_map_0_1', 'singapore-queenstown_map_1_1', 'singapore-queenstown_map_0_2', 'singapore-queenstown_map_3_0', 'singapore-queenstown_map_2_1', 'singapore-queenstown_map_1_0', 'singapore-queenstown_map_0_3', 'singapore-queenstown_map_2_0', 'singapore-queenstown_map_2_3', 'singapore-queenstown_map_1_3', 'singapore-queenstown_map_2_2',
>  'singapore-hollandvillage_map_0_2', 'singapore-hollandvillage_map_2_0', 'singapore-hollandvillage_map_1_0', 'singapore-hollandvillage_map_1_3', 'singapore-hollandvillage_map_3_3', 'singapore-hollandvillage_map_2_3', 'singapore-hollandvillage_map_2_1', 'singapore-hollandvillage_map_1_1', 'singapore-hollandvillage_map_3_2', 'singapore-hollandvillage_map_0_1', 'singapore-hollandvillage_map_0_3']

Is this because the samples we used for training  only invovle this 47 maps?
BTW when training on the mini dataset, the gpu_city_list number is 9.

**Comment by abbyxxn** [comment]
Yes, the samples we used for training only involved these 47 maps. gpu_city_list means we need to create these map tiles on each gpu so that we can use the prediction of the sample to update them.

**Comment by xuwanyan1998** [comment]
> > 
> 
> When I train the model on the 0.1-trainval dataset, I set the batchsize=1, using 1 gpu, when devide the map tiles for each gpu, the gpu_city_list number is 47, like
> 
> > ['boston-seaport_map_2_1', 'boston-seaport_map_1_2', 'boston-seaport_map_0_3', 'boston-seaport_map_3_1', 'boston-seaport_map_1_1', 'boston-seaport_map_0_2', 'boston-seaport_map_2_2', 'boston-seaport_map_0_0', 'boston-seaport_map_1_3', 'boston-seaport_map_0_1', 'boston-seaport_map_1_0', 'boston-seaport_map_3_2',
> > 'singapore-onenorth_map_1_2', 'singapore-onenorth_map_0_1', 'singapore-onenorth_map_2_3', 'singapore-onenorth_map_2_2', 'singapore-onenorth_map_1_1', 'singapore-onenorth_map_1_3', 'singapore-onenorth_map_0_2', 'singapore-onenorth_map_3_1', 'singapore-onenorth_map_3_0', 'singapore-onenorth_map_2_1', 'singapore-onenorth_map_2_0', 'singapore-onenorth_map_0_0', 'singapore-onenorth_map_3_2',
> > 'singapore-queenstown_map_0_1', 'singapore-queenstown_map_1_1', 'singapore-queenstown_map_0_2', 'singapore-queenstown_map_3_0', 'singapore-queenstown_map_2_1', 'singapore-queenstown_map_1_0', 'singapore-queenstown_map_0_3', 'singapore-queenstown_map_2_0', 'singapore-queenstown_map_2_3', 'singapore-queenstown_map_1_3', 'singapore-queenstown_map_2_2',
> > 'singapore-hollandvillage_map_0_2', 'singapore-hollandvillage_map_2_0', 'singapore-hollandvillage_map_1_0', 'singapore-hollandvillage_map_1_3', 'singapore-hollandvillage_map_3_3', 'singapore-hollandvillage_map_2_3', 'singapore-hollandvillage_map_2_1', 'singapore-hollandvillage_map_1_1', 'singapore-hollandvillage_map_3_2', 'singapore-hollandvillage_map_0_1', 'singapore-hollandvillage_map_0_3']
> 
> Is this because the samples we used for training only invovle this 47 maps? BTW when training on the mini dataset, the gpu_city_list number is 9.


In my understanding, each of these 4 maps is represented by 4*4 tiles. At the beginning of each epoch, when **take_map_prior/replace_map_prior** and assigning different tiles for different GPUs(which in my case is all tiles assigned to GPU 0), only 47 map tiles associated with the training samples(which is 9 tails for mini dataset). I'm not sure if this understanding is correct

**Comment by xuwanyan1998** [comment]
> Yes, the samples we used for training only involved these 47 maps. gpu_city_list means we need to create these map tiles on each gpu so that we can use the prediction of the sample to update them.

Thanks for your reply! Still try to understand this project(so complicated), hopes to discuss with you when encounter other problems in the future : )

**Comment by abbyxxn** [comment]
> Thanks for your reply! Still try to understand this project(so complicated), hopes to discuss with you when encounter other problems in the future : )
Your understanding is correct. To save memory, we only created map tiles with samples. Instead of creating 4*4 map tiles for the four cities, we only created 47 map tiles.

**Comment by abbyxxn** [comment]
> > > 
> > 
> > 
> > When I train the model on the 0.1-trainval dataset, I set the batchsize=1, using 1 gpu, when devide the map tiles for each gpu, the gpu_city_list number is 47, like
> > > ['boston-seaport_map_2_1', 'boston-seaport_map_1_2', 'boston-seaport_map_0_3', 'boston-seaport_map_3_1', 'boston-seaport_map_1_1', 'boston-seaport_map_0_2', 'boston-seaport_map_2_2', 'boston-seaport_map_0_0', 'boston-seaport_map_1_3', 'boston-seaport_map_0_1', 'boston-seaport_map_1_0', 'boston-seaport_map_3_2',
> > > 'singapore-onenorth_map_1_2', 'singapore-onenorth_map_0_1', 'singapore-onenorth_map_2_3', 'singapore-onenorth_map_2_2', 'singapore-onenorth_map_1_1', 'singapore-onenorth_map_1_3', 'singapore-onenorth_map_0_2', 'singapore-onenorth_map_3_1', 'singapore-onenorth_map_3_0', 'singapore-onenorth_map_2_1', 'singapore-onenorth_map_2_0', 'singapore-onenorth_map_0_0', 'singapore-onenorth_map_3_2',
> > > 'singapore-queenstown_map_0_1', 'singapore-queenstown_map_1_1', 'singapore-queenstown_map_0_2', 'singapore-queenstown_map_3_0', 'singapore-queenstown_map_2_1', 'singapore-queenstown_map_1_0', 'singapore-queenstown_map_0_3', 'singapore-queenstown_map_2_0', 'singapore-queenstown_map_2_3', 'singapore-queenstown_map_1_3', 'singapore-queenstown_map_2_2',
> > > 'singapore-hollandvillage_map_0_2', 'singapore-hollandvillage_map_2_0', 'singapore-hollandvillage_map_1_0', 'singapore-hollandvillage_map_1_3', 'singapore-hollandvillage_map_3_3', 'singapore-hollandvillage_map_2_3', 'singapore-hollandvillage_map_2_1', 'singapore-hollandvillage_map_1_1', 'singapore-hollandvillage_map_3_2', 'singapore-hollandvillage_map_0_1', 'singapore-hollandvillage_map_0_3']
> > 
> > 
> > Is this because the samples we used for training only invovle this 47 maps? BTW when training on the mini dataset, the gpu_city_list number is 9.
> 
> In my understanding, each of these 4 maps is represented by 4*4 tiles. At the beginning of each epoch, when **take_map_prior/replace_map_prior** and assigning different tiles for different GPUs(which in my case is all tiles assigned to GPU 0), only 47 map tiles associated with the training samples(which is 9 tails for mini dataset). I'm not sure if this understanding is correct

Your understanding is correct. To save memory, we only created map tiles that contain samples. Instead of creating 4*4 map tiles for the four cities, we only created 47 map tiles.

**Comment by abbyxxn** [comment]
> Thanks for your reply! Still try to understand this project(so complicated), hopes to discuss with you when encounter other problems in the future : )

You're welcome~ Feel free to reach out anytime if you encounter any other issues.
