### ISSUE TITLE
Question about the train data and test data

### ISSUE THREAD

**Issue by ypfFromWhu** [Tsinghua-MARS-Lab/neural_map_prior#6]
I have noticed that  we train the model with the input of the Surrounding Camera Images and Global Neural Map Prior. How can we get the Neural Map Prior of the train data and test data? I guess that we run all the scenes by the base models such as BevFormer to get it and then use it to train the BevFormer+NMP using the same data. Do I understand correctly?

**Comment by abbyxxn** [comment]
Sorry for the late reply. The neural map prior is initially empty. Once features are stored into it, these features can serve as a prior. The initial input consists only of camera images, and gradually, each location has its neural map prior.

**Comment by ypfFromWhu** [comment]
你好，你的邮件我已收到，会尽快给你回复。
