### ISSUE TITLE
question about testing model

### ISSUE THREAD

**Issue by mojiadi** [Tsinghua-MARS-Lab/neural_map_prior#7]
Both testing and training the model are conducted on the nuScene dataset.I want to prepare my own dataset to test the model,What should I modify the code?

**Comment by abbyxxn** [comment]
Basically,  you only need to modify the maximum and minimum geographical locations of the map in the [lane_render.py](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/project/neural_map_prior/map_tiles/lane_render.py#L16) file, using the following four variables: train_min_geo_loc, train_max_geo_loc, val_min_geo_loc, val_max_geo_loc. Also, make sure to keep the [info.pkl](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/project/neural_map_prior/map_tiles/lane_render.py#L213) and [city_info.pkl](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/project/neural_map_prior/map_tiles/lane_render.py#L223) files consistent with those of the nuscenes dataset.
