### ISSUE TITLE
neural map prior + MapTR

### ISSUE THREAD

**Issue by mohamedsamirx** [Tsinghua-MARS-Lab/neural_map_prior#9]
is it possible to merge neural map prior as an online hd map construction model with the idea of neural map prior ?
how can it be done

**Comment by abbyxxn** [comment]
Yes, the neural map prior can be integrated with various online HD map construction methods. If you already have a basic online mapping model, you can combine it with the neural map prior by referring to the method described [here](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/project/neural_map_prior/models/mapers/original_hdmapnet.py#L110). Essentially, the update and training processes for the neural map are encapsulated within this [file](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/project/neural_map_prior/map_tiles/lane_render.py) and this [file](https://github.com/Tsinghua-MARS-Lab/neural_map_prior/blob/e0a8188a40e7a701b8c355b3c90c758310557998/project/neural_map_prior/models/mapers/map_global_memory.py). You just need to determine which features to store and update.
